#!/bin/bash
# Philip Roberts Jul 25, 2021

# Bash Aliases
alias e='exit'
alias c='clear'
alias l='ls -la'
alias py='python3'
alias extract="tar -xvf"

# PS1
# user@host <current dir> >
export PS1="\u@\H \W > \[$(tput sgr0)\]"

# Path Variables
export PATH=$PATH:/usr/local/go/bin
export GOPATH=/home/philip/.local/go
export PATH=$PATH:$(go env GOPATH)/bin

