#!/bin/bash
# Philip Roberts Jul 25, 2021

# Bash Aliases
alias e='exit'
alias c='clear'
alias l='ls -la'
alias cdh="cd /mnt/c/users/Philip/Documents"
alias v="vim"

# Tmux Aliases
alias ta="tmux attach"
alias td="tmux detach"
alias tls="tmux ls"
alias tas="tmux attach -t "

# Utilities
alias py='python3'
alias r='py m.py'
alias extract="tar -xvf"
alias b="vim ~/.bashrc"
alias t="vim ~/.tmux.conf"
alias tree="tree -a"

# Check Battery
alias bp="powershell.exe '[console]::beep(261.6, 700)'"
#alias battery="cat /sys/class/power_supply/battery/capacity"
#alias batterystatus="watch -n 30 cat /sys/class/power_supply/battery/capacity"

# Compile main.cpp (for CSCI 303)
alias compile="g++ -std=c++11 main.cpp -o main"
alias comprun="rm -f ./main; compile && ./main"

# user@host <current dir> 
export PS1="\u@pc \W > \[$(tput sgr0)\]"

# Rust Environment
. "$HOME/.cargo/env"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
c
