#!/bin/bash
# Philip Roberts Jul 25, 2021

# Bash Aliases
alias e='exit'
alias c='clear'
alias l='ls -la'
alias py='python3'
alias extract="tar -xvf"
alias bp="powershell.exe '[console]::beep(261.6, 700)'"
alias battery="cat /sys/class/power_supply/battery/capacity"

# PS1
# user@host <current dir> >
export PS1="\u@\H \W > \[$(tput sgr0)\]"

cd /mnt/c/users/Philip/Documents
